# Generated by Django 4.1.1 on 2022-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoClientes',
            fields=[
                ('tipoid', models.AutoField(db_column='TipoId', primary_key=True, serialize=False)),
                ('tipo', models.TextField(db_column='Tipo')),
            ],
            options={
                'db_table': 'tipo_clientes',
                'managed': False,
            },
        ),
    ]
